Task 1 Semester 7 var 2
sergey-berezin/401_senotova pull request #1
Opened 2023-10-24 00:05 UTC by SenotovaYulia

2023-10-24 07:22 UTC, sergey-berezin requested changes

2023-10-24 07:22 UTC, sergey-berezin commented on .gitignore
> +/.vs/ONNX detect/v17/.futdcache.v2
Достаточно указать .vs

2023-10-24 07:22 UTC, sergey-berezin commented on ONNX detect.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ONNX detect", "ONNX detect\ONNX detect.csproj", "{A925A728-D2FB-41A1-8BAC-5B73ABEF6747}"
Необходимо создать два проекта, при этом консольное приложение подключает компонент как пакет NuGet.

2023-10-25 12:32 UTC, sergey-berezin requested changes
В этом PR есть три файла ClassDetection.cs в разных папках. Они все нужны?

2023-10-25 13:19 UTC, SenotovaYulia commented
Нет, нужен только Task1 2 proj/Nuget Detect/Nuget Detect/ClassDetection.cs. Я сейчас удалю ненужные папки и файлы.

2023-10-26 07:49 UTC, merged